# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TOPODATADowloader
                                 A QGIS plugin
 Plugin to download TOPODATA grid tiles in GeoTIFF format.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-19
        copyright            : (C) 2026 by Ana Freitas
        email                : ana.freitas@ime.eb.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TOPODATADowloader class from file TOPODATADowloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TOPODATA_Dowloader import TOPODATADowloader
    return TOPODATADowloader(iface)
