# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TOPODATADowloaderDialog
                                 A QGIS plugin
 Plugin to download TOPODATA grid tiles in GeoTIFF format.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ana Freitas
        email                : ana.freitas@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsMessageLog
from .DOWLOADER import Downloader, buscar_href_altitude
from .quadriculas_zn import QUADRICULAS_ZN
from .LAYERLOADER import LayerLoader
from qgis.PyQt.QtWidgets import QLabel, QVBoxLayout
from qgis.PyQt.QtGui import QPixmap


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'TOPODATA_Dowloader_dialog_base.ui'),
    from_imports=True,
    import_from='TOPODATA_Dowloader')


class TOPODATADowloaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(TOPODATADowloaderDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.pushButton.clicked.connect(self.botaoparadowload)
        self.pushButton_2.clicked.connect(self.botaoparaabrirmapaindice)


        self.listWidget.clear()
        for codigo in QUADRICULAS_ZN:
            self.listWidget.addItem(codigo)

    def botaoparadowload(self):
        QgsMessageLog.logMessage("Arquivo Baixado", "Plugin")

        quadricula = self.listWidget.currentItem().text()

        href = buscar_href_altitude(quadricula)
        print("Link encontrado:", href)

        obj_teste = LayerLoader(href, self.mQgsFileWidget.filePath())
        obj_teste.download_raster_layer(quadricula + "ZN", progress_callback=self.progressBar.setValue)

    def botaoparaabrirmapaindice(self):
            QgsMessageLog.logMessage("Mapa Índice aberto", "Plugin")

            caminho_imagem = os.path.join(os.path.dirname(__file__), "mapaindice.jpg")

            janela_mapa = QtWidgets.QDialog(self)
            janela_mapa.setWindowTitle("Mapa Índice - TOPODATA")

            label_imagem = QLabel()
            pixmap = QPixmap(caminho_imagem)
            label_imagem.setPixmap(pixmap)

            layout = QVBoxLayout()
            layout.addWidget(label_imagem)
            janela_mapa.setLayout(layout)

            janela_mapa.exec_()